### PR TITLE
Completion handler is not called

### PR DESCRIPTION
**Pull request by apfritts**
The provided `completionHandler` is being saved to the `remoteNotificationCallbacks` dictionary, but the native `onFinishRemoteNotification:(NSString *)notificationId fetchResult:(UIBackgroundFetchResult)result` function didn't actually lookup and call the completion handler.

I believe this fixes that bug and addresses #216 #244 #297 as well.

### CODE REVIEW

**Comment by leethree** [comment]
Looks great. I think the example project needs to be updated as well 👍🏼

**Comment by apfritts** [comment]
@leethree I updated the example project and rebased my PR. I still need to re-confirm that this is functioning properly before it gets merged since there seem to have been quite a few other commits since I opened this.

**Review by tavour-frank — APPROVED** [review]

**Review by tavour-frank — APPROVED** [review]

**Review by nicolas6422 — APPROVED** [review]

**Review by Naturalclar — APPROVED** [review]
LGTM

**Comment by chrisbobbe** [comment]
This merged work looks like an approximate revert of 1506ddf36 / #241, which was marked as addressing #163. Do we expect #163 not to be re-introduced?

**Comment by floydkim** [comment]
@chrisbobbe @Naturalclar
I'm experiencing this issue https://github.com/react-native-push-notification/ios/issues/163 after bumping to 1.11.0. (previously 1.10.1)
I think, in my project, there's some duplicated handling of FCM event.
(I'm using a couple of libraries that deal with FCM events.)

I think we need to be clear about the responsibilities of this library.

**Pull request merged**
